In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
ran = 4567


In [3]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()
print(iris_dataset['feature_names'])
print(iris_dataset['target_names'])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], random_state=ran, test_size=0.5)
print(X_train.shape, ' ', X_test.shape)

(75, 4)   (75, 4)


In [5]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5,weights='uniform')
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [6]:

knn.score(X_test,y_test)

0.9733333333333334

In [7]:
knnd = KNeighborsClassifier(n_neighbors=3,weights='distance')
knnd.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3, weights='distance')

In [8]:
knnd.score(X_test, y_test)

0.96

In [9]:
from sklearn.metrics import confusion_matrix
ypred = knn.predict(X_test)
confusion = confusion_matrix(y_test,ypred)
print(confusion)

[[26  0  0]
 [ 0 21  1]
 [ 0  1 26]]
